---
- name: Install CNI (Calico)
  hosts: "{{ host }}"
  gather_facts: no 
  become: yes 
  remote_user: "{{ user }}"

  tasks:

    - name: Install calico CNI (tigera-operator)
      shell: "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.3/manifests/tigera-operator.yaml"
      
    - name: Install calico CNI (custom-resources)
      shell: "curl https://raw.githubusercontent.com/projectcalico/calico/v3.27.3/manifests/custom-resources.yaml -O"
    
    - name: Create CNI (custom-resources)
      shell: "kubectl apply -f custom-resources.yaml"

    - name: Remove taints for node (one-node cluster)
      shell: "kubectl taint nodes --all node-role.kubernetes.io/master-"
