---
- name: Init cluster
  hosts: "{{ host }}"
  gather_facts: no 
  become: yes 
  remote_user: "{{ user }}"

  tasks:
    - name: Init cluster
      shell: "sudo kubeadm init --pod-network-cidr=192.168.0.0/16"

    # TODO: add kubectl get pods stdout print out to see if everything is ok
