---
- name: Install CNI (Calico)
  hosts: "{{ host }}"
  gather_facts: no 
  become: yes 
  remote_user: "{{ user }}"

  tasks:

    - name: Install calico CNI (tigera-operator)
      shell: "sudo kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/tigera-operator.yaml"

    - name: Install calico CNI (custom-resources)
      shell: "sudo kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/custom-resources.yaml"

    - name: Remove taints
      shell: "sudo kubectl taint nodes --all node-role.kubernetes.io/control-plane-"
