---
- name: Install dependencies for debian12
  hosts: "{{ host }}"
  gather_facts: no 
  become: yes
  remote_user: "{{ user }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Disable swap 
      shell: |
        swapoff -a

    - name: Disable swap in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Install ca certs etc...
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - vim 
    
    - name: copy install script
      copy:
        src: ./scripts/install_k8s.sh
        dest: /tmp/install_k8s.sh
        mode: u=rwx,g=rx,o=rx

    - name: install k8s, docke and containerd using shell script
      shell: "/tmp/install_k8s.sh"
      ignore_errors: true
      async: 1200
      poll: 10

    - name: Install Ansible
      apt:
        name: ansible
        state: present
    
    - name: Download k9s deb package 
      shell: "wget https://github.com/derailed/k9s/releases/download/v0.32.4/k9s_linux_amd64.deb"
