- hosts: all
  become: yes
  tasks:
    - name: Apt update
      apt:
        update_cache: yes

    - name: Adding repos 
      shell: curl -fSsL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /usr/share/keyrings/postgresql.gpg > /dev/null

    - name: Addot apt repo
      shell: echo deb [arch=amd64,arm64,ppc64el signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main | sudo tee /etc/apt/sources.list.d/postgresql.list

    - name: Installing PostgreSQL16 
      apt: 
        name: postgresql
        state: latest

    - name: Enable PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Install psycopg2
      ansible.builtin.pip:
        name: psycopg2-binary~=2.8.6

    - name: postgresql.conf change
      ansible.builtin.lineinfile:
              path: /etc/postgresql/16/main/postgresql.conf
              line: '{{item}}'
              owner: postgres
              group: postgres
              mode: '0644'
      with_items:
              - "listen_addresses = '*'"
              

    - name: pg_hba configuration
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/16/main/pg_hba.conf
        state: present
        contype: host
        databases: all
        source: "0.0.0.0/0"
        method: md5
        users: all
  
    - name: Restart PostgreSQL
      service:
              name: postgresql
              state: restarted
